# This is a basic workflow to help you get started with Actions
name: CI
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
    - 'main'
    paths:
    - 'Version'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Update Dockerfile
        run: |
          sed -i -e "s/GIT_R_VERSION/$(cat Version)/" Dockerfile   
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Artifcatory
        uses: jfrog/setup-jfrog-cli@v2
        env:
            # JFrog platform url (for example: https://acme.jfrog.io) 
            JF_URL: https://rahul3296.jfrog.io/
    
            # Basic authentication credentials
            JF_USER: ${{ secrets.JF_USER }}
            JF_PASSWORD: ${{ secrets.JF_PASSWORD }}  
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: myimage:latest
          
      -
        name: Push to artficatory
        run: |
          docker images
          docker login -u rahu.3296@gmail.com -p Jackadv@1 rahul3296.jfrog.io
          docker tag myimage:latest rahul3296.jfrog.io/rahul3296/myimage
          docker push rahul3296.jfrog.io/rahul3296/myimage
      
